var arrLang = {
      "us": {
        "ds": "Days",
        "hs": "Hours",
        "ms": "Min",
        "ss": "Sec",
        "ieostart": "ieo starts in",
        "ieoend": "ieo ends",
        "ieo2start": "ieo 2 starts",
        "ieo2end": "ieo 2 ends",
        "ieo3start": "ieo 3 starts",
        "ieo3end": "ieo 3 ends",
        "cookietop": "We use cookies to tailor our services and online advertising.",
        "cookielink": "By using our website you agree with our <a target='_blank' style='color:#ffd788;' href='/cookiepolicy'>Cookie Policy</a>.",
        "about": "About",
        "roadmap": "Roadmap",
        "ourdevs": "Developers",
        "ourteam": "Team",
        "pitch": "Pitch Deck",
        "demo": "Demo",
        "signin": "SIGN IN",
        "header": "The fashion discovery platform",
        "description": "Discover Styles. Earn Crypto.",
        "p2p": "BUY ON P2PB2B (KYC)",
        "airswap": "BUY VIA AIRSWAP (NO KYC)",
        "signin": "SIGN IN",
        "featured": "As featured on",
        "unisex": "UNISEX",
        "abouttext": "<span><span class='white about__text--first lang'><img src='img/sprites/intermediate-svg/mini-logo.svg' alt=''><span>CURATE </span></span></span>is a style discovery decentralized app (DApp) i.e 'blockchain smart contract enabled' platform, which rewards you with digital tokens in the form of BTC, ETH and our own CUR8 tokens in return for users curating fashion styles.",
        "abouttexttwo": "Fashion brands and retailers have partnered up with Curate to showoff their latest styles, raise brand awareness and increase their online sales.",
        "abouttextthree": "In return, Curate provides a trustless platform allowing users to feedback a curated collection of fashion styles for the community to discover.",
        "abouttextfour": "To put simply, Fashion brands partner up with Curate and we pass on the rewards to the curators and discoverer's.",
        "abouttextfive": "We are: Decentralised. Web 3.0. Open Source.",
        "how": "How it works",
        "howtext": "CURATE is based on the ethereum blockchain utilizing the ERC&mdash;20 token system in the form of our utlity token, the CUR8 token.",
        "howtexttwo": "The CURATE platform being a DApp means it's decentralised and distributed system of service is run and hosted by numerous systems around the globe.",
        "howtextthree": "All data in our platform is secured by cryptography. We are decentralised, open source and web 3.0.",
        "howrow": "Content user (i.e brand or fashionista) uploads fashion content to Curate",
        "howrowtwo": "'Curator' community engages and upvotes fashion content",
        "howrowthree": "Content gains popularity allowing 'discoverer' community to discover content",
        "howrowfour": "Curate rewards both original content user, curator and discover users with BTC, ETH and CUR8 tokens",
        "howrowfive": "CUR8 token holders can use the tokens to redeem discount codes, promo offers and more on Curate",
        "demoheader": "Curate Demo Preview",
        "qone": "Concept created by founder, James Hakim",
        "qonetwo": "White paper first draft created",
        "qonethree": "Busines plan first draft completed",
        "qtwo": "Curate team members recruited",
        "qtwotwo": "Website and social media/telegram group created",
        "qtwothree": "Demo preview of platform designed",
        "qthree": "PRE-IEO seed round complete",
        "qthreetwo": "10,000+ telegram members active",
        "qthreethree": "Approved for 1st IEO listing on P2PB2B.io",
        "qfour": "1st IEO starts, aiming to raise $2.25M USD",
        "qfourtwo": "Development officially starts on Curate platform",
        "qfourthree": "CUR8 token is listed on two exchanges, P2PB2B.io and WhiteBit.io and begins trading",
        "twentyqone": "2nd IEO starts on two top CoinMarketCap approved exchanges",
        "twentyqonetwo": "Private-alpha launch of Curate platform open to telegram members",
        "twentyqonethree": "CUR8 token listed on two more top exchanges, volume of trading increase",
        "twentyqtwo": "3rd IEO starts on a DEX",
        "twentyqtwotwo": "Public-beta version launched available to new members",
        "twentyqtwothree": "Curate reaches 10,000 active monthly users using the platform and app",
        "twentyqtwofour": "Start of application development",
        "design": "Chief Design Officer",
        "senioradm": "Senior Administrator",
        "ceo": "Chief Executive Officer &amp; Founder",
        "blockchaindev": "Blockchain Engineer",
        "marketingadv": "Marketing Advisor",
        "salesofficer": "Chief Sales Officer and HR",
        "commmanager": "Chief Community Manager",
        "contmanager": "Content Manager",
        "lawyer": "Certified Blockchain Lawyer",
        "pubrelat": "Head of Public Relations",
        "innovations": "Head of Innovation",
        "smm": "Social Media Manager",
        "digitalmanager": "Social and Digital Manager",
        "operationsman": "Operations Manager",
        "businessofficer": "Chief Business Officer",
        "marketingofficer": "Chief Marketing Officer",
        "retail": "Retail Applicants",
        "exchange": "Exchange Partners",
        "p2pannounce": "Curate is now <span class='news-highlight'>confirmed to be listed on P2PB2B</span> trading platform. P2PB2B is one of the top 20 exchanges in the world with a daily trading volume of",
        "p2pbold": "$418 million - a real powerhouse.",
        "ceocurate": "CEO Curate",
        "distribution": "Token distribution",
        "ieophaseone": "IEO Phase 1",
        "ieophasetwo": "IEO Phase 2",
        "ieophasethree": "IEO Phase 3",
        "ieoteam": "Team",
        "ieopartner": "Partnerships",
        "bounties": "Bounties",
        "commevents": "Community events",
        "fundsalloc": "Funds allocation",
        "development": "Development",
        "marteting": "Marketing",
        "legal": "Legal",
        "bounty": "General &amp; Admin expenses",
        "banking": "Banking &amp; Reserve",
        "revenue": "Revenue Model",
        "revenueone": "Curate, the original fashion discovery platform, will steadily grow the value of the platform and $CUR8 tokens by increasing demand and use cases by <span>adding new participating retailers, extending niches outside fashion retail via 'Curate +' and by providing enough liquidity.</span>",
        "revenuetwo": "Curate Pro membership for retailers, initial fee $149/year offering retailers enhanced membership <span>including featured listings, verified badge status, more engagement activities such as rewarding users directly with CUR8 tokens.</span> Free to those who opt-in for the affiliate programme i.e amazon associates affiliate, <span>earning curate up to 10% on sales.</span>",
        "revenuethree": "Curate Ads, <span>our in-built native advertising platform offered to advertisers and agencies</span>, allows custom targeting and ad placements to our users who have opted-in yielding a high ROI and RPM.",
        "revenuefour": "Curate +, our native browser extension <span>allows users to earn free BTC and CUR8 as cashback when they shop online through a commission deal.</span> Using our existing partnerships from the curate platform, the Curate + extension extends to all niches outside fashion <span>increasing market adoption of Curate and $CUR8 tokens.</span>",
        "revenuefive": "$CUR8 tokens offered for sale on the platform, which <span>can be used to redeem coupons, get free shipping and get cash back</span> at participating retailers on the platform, as well as level up user accounts for more features.",
        "retailer": "Retailer benefits",
        "retailerone": "Raised <span>brand awareness</span>",
        "retailertwo": "<span>Increased traffic</span> to merchant sites and goal conversions",
        "retailerthree": "Clothing ranges and seasonal wears <span>listed  on the largest open/transparent platform</span> leveraging blockchain technology.",
        "retailerfour": "<span>Access to 50,000 users</span> upon launch for curated feedback on their fashion range.",
        "retailerfive": "On-site analytics and tracking pixel leading to <span>increased sales through optimization.</span>",
        "retailersix": "<span>Prevent fraud transactions </span>and chargebacks as users will be verified <span>via KYC</span> to ensure authenticity.",
        "retailerseven": "<span>Zero commission</span> will be taken from Curate for all successful leads giving retailers bigger profits and customers better prices.",
        "retailereight": "<span>QR barcodes supplied to all partneredclothing brands</span> to verify authenticity throughout the supply chain preventing fake merchandise.",
        "lexfuturis": "Curate including CUR8 tokens are represented by international law firm & consultancy Lex Futurus Group.",
        "policy": "Privacy Policy",
        "howitwrks": "How it works",
        "totop": "TO TOP",
        "ambassador": "Ambassador",
        "usecasehdr": "CUR8 Use Cases",
        "usecasetext": "CUR8 tokens serve as a multi-use utility token offering users a wide<br>number of use cases on both the Curate DApp and outside the Curate ecosystem.<br><br>– Purchase items on the Curate platform using CUR8 tokens<br>– Unlock special discounts on items such as 10% off coupons<br>– Redeem free shipping when shopping on the platform<br>– Upgrade account to Curate Pro to unlock more features<br>– Social karma tipping for retailers to offer bounties to users for reviews or perform certain activities i.e like their content<br>– Use as a monetary currency for payments outside of the Curate ecosystem with our partners.<br>– Plus many more to be added as we go live"
      },
      "ru": {
        "ds": "Дней",
        "hs": "Часов",
        "ms": "Минут",
        "ss": "Секунд",
        "ieostart": "ieo начнется",
        "ieoend": "ieo закончится",
        "ieo2start": "ieo 2 начнется",
        "ieo2end": "ieo 2 закончится",
        "ieo3start": "ieo 3 начнется",
        "ieo3end": "ieo 3 закончится",
        "cookietop": "Мы используем куки чтобы улучшать наши сервисы и быть релевантными.",
        "cookielink": "Находясь на нашем сайте вы соглашаетесь с <a target='_blank' style='color:#ffd788;' href='/cookiepolicy'>Политика Cookie</a>.",
        "about": "О нас",
        "roadmap": "Дорожная карта",
        "ourdevs": "Разработчики",
        "ourteam": "Команда",
        "pitch": "Pitch Deck",
        "demo": "Демо",
        "signin": "Войти",
        "header": "Платформа по обзору моды",
        "description": "Делитесь стилями, получайте крипту!",
        "p2p": "Купить на P2PB2B (KYC)",
        "airswap": "Купить с AIRSWAP (NO KYC)",
        "signin": "Войти",
        "featured": "О нас пишут",
        "unisex": "УНИСЕКС",
        "abouttext": "<span><span class='white about__text--first lang'><img src='img/sprites/intermediate-svg/mini-logo.svg' alt=''><span>CURATE </span></span></span>является децентрализованным приложением в котором люди делятся модными тендценциями (DApp), то есть платформой на базе смарт–контрактов сети блокчейн, которая вознаграждает вас цифровыми токенами в виде BTC, ETH и нашими собственными токенами CUR8 в обмен на пользователей, поддерживающих модные тенденции.",
        "abouttexttwo": "Бренды и продавцы сотрудничают с Curate, чтобы показать свои последние стили, повысить узнаваемость бренда и увеличить свои онлайн-продажи.",
        "abouttextthree": "В свою очередь, Curate предоставляет надежную платформу, позволяющую пользователям делиться отзывами о модных вещах, которые увидят все.",
        "abouttextfour": "Проще говоря, бренды сотрудничают с Curate, и мы передаем награды кураторам и первооткрывателям.",
        "abouttextfive": "Мы: децентрализованны. Веб 3.0. Открытый исходный код.",
        "how": "Как это работает",
        "howtext": "CURATE основан на блокчейне Ethereum, использующем систему токенов ERC - 20 в формате utlity–токена CUR8.",
        "howtexttwo": "Платформа CURATE – DApp, это значит, что ее децентрализованная и распределенная система обслуживания запущена и размещена в многочисленных системах по всему миру.",
        "howtextthree": "Все данные на нашей платформе защищены криптографией. Мы децентрализованы, с открытым исходным кодом и веб 3.0.",
        "howrow": "Пользователь контента (то есть бренд или обычный пользователь) загружает контент моды в Curate.",
        "howrowtwo": "'Curator' сообщество привлекает и поддерживает модный контент",
        "howrowthree": "Контент набирает популярность, позволяя сообществу первооткрывателей находить контент",
        "howrowfour": "Curate награждает как автора контента, так и куратора и пользователей – BTC, ETH и CUR8 токенами.",
        "howrowfive": "Владельцы токенов CUR8 могут использовать токены для погашения скидочных кодов, промо-предложений и многого другого в Curate.",
        "demoheader": "Пердпросмотр Curate–Демо",
        "qone": "Концепция создана основателем, James Hakim",
        "qonetwo": "Первый набросок White paper завершен",
        "qonethree": "Первый набросок бизнес–плана завершен",
        "qtwo": "Отобрана команда Curate",
        "qtwotwo": "Сайт и соц.группы в т.ч. телеграм созданы",
        "qtwothree": "Нарисовано демо платформы",
        "qthree": "PRE-IEO посевной раунд закончен",
        "qthreetwo": "10,000+ пользователей телеграм",
        "qthreethree": "Утверждены для 1st IEO на P2PB2B.io",
        "qfour": "1–й IEO начался, цель – собрать $2.25M долларов",
        "qfourtwo": "Старт разработки над платформой Curate",
        "qfourthree": "Токен CUR8 котируется на двух биржах, P2PB2B.io и WhiteBit.io",
        "twentyqone": "2–е IEO на двух подтвержденных CoinMarketCap обменниках",
        "twentyqonetwo": "Закрытый альфа-запуск платформы Curate, открытый для членов телеграм группы",
        "twentyqonethree": "Токен CUR8 котируется еще на двух ведущих биржах, объем торгов увеличивается",
        "twentyqtwo": "3–й IEO на DEX",
        "twentyqtwotwo": "Открытая публичная бета-версия доступна для новых участников",
        "twentyqtwothree": "Curate достигает 10 000 активных пользователей ежемесячно, используя платформу и приложение",
        "twentyqtwofour": "Начало разработки приложения",
        "design": "Шеф – дизайнер",
        "senioradm": "Главный администратор",
        "ceo": "Исполнительный директор и основатель",
        "blockchaindev": "Блокчейн инженер",
        "marketingadv": "Консультант по маркетингу",
        "salesofficer": "Директор по продажам и персоналу",
        "commmanager": "Главный менеджер сообщества",
        "contmanager": "Контент менеджер",
        "lawyer": "Сертифицированный блокчейн юрист",
        "pubrelat": "Начальник отдела по связям с общественностью",
        "innovations": "Руководитель отдела инноваций",
        "smm": "Менеджер по социальным медиа",
        "digitalmanager": "Социальный и цифровой менеджер",
        "operationsman": "Операционный менеджер",
        "businessofficer": "Директор по бизнесу",
        "marketingofficer": "Директор по маркетингу",
        "retail": "Розничные кандидаты",
        "exchange": "Партнеры по обмену",
        "p2pannounce": "В настоящее время подтверждено, что <span class='news-highlight'>Curate работает с P2PB2B</span>. P2PB2B является одной из 20 ведущих бирж в мире с ежедневным объемом торгов в",
        "p2pbold": "418 000 000 долларов.",
        "ceocurate": "Основатель Curate",
        "distribution": "Распределение токенов",
        "ieophaseone": "IEO 1",
        "ieophasetwo": "IEO 2",
        "ieophasethree": "IEO 3",
        "ieoteam": "Команда",
        "ieopartner": "Партнерские отношения",
        "bounties": "Баунти",
        "commevents": "Общественные мероприятия",
        "fundsalloc": "Распределение средств",
        "development": "Разработка",
        "marteting": "Маркетинг",
        "legal": "Юриспруденция",
        "bounty": "Общие &amp; Административные расходы",
        "banking": "Банк &amp; Резерв",
        "revenue": "Модель дохода",
        "revenueone": "Curate, оригинальная платформа для поиска модных тенденций, будет постоянно увеличивать ценность платформы и токенов $CUR8, увеличивая спрос и возможности использования, <span>добавляя новых участвующих розничных продавцов, расширяя ниши вне розничной торговли модными товарами через «Curate +» и обеспечивая достаточную ликвидность.</span>",
        "revenuetwo": "Членство в Curate Pro для розничных продавцов, начальная плата в размере $ 149 / год, предлагает розничным продавцам расширенное членство <span>, включая избранные списки, подтвержденный профиль, дополнительные мероприятия по вовлечению, такие как вознаграждение пользователей напрямую токенами CUR8. </span> Бесплатно для тех, кто подписан на партнерскую программу Amazon Associates, выгода до 10% с продажах.",
        "revenuethree": "Curate реклама, <span>наша встроенная нативная рекламная платформа, предлагаемая рекламодателям и агентствам</span>, позволяет настраивать таргетинг и размещение рекламы для наших пользователей, которые выбрали высокий уровень «ROI» и «RPM».",
        "revenuefour": "Curate +, наше нативное расширение для браузера <span>позволяет пользователям зарабатывать бесплатные BTC и CUR8 в качестве кешбэка, когда они совершают покупки онлайн, соглашаясь с комиссией.</span> Используя партнерские отношения с платформой Curate, расширение Curate + распространяется на все ниши вне моды <span>увеличивая распространение на рынке токенов Curate и $CUR8.</span>",
        "revenuefive": "Токены $ CUR8 выставлены на продажу на платформе, которая <span>может быть использован для погашения купонов, получения бесплатной доставки и кэшбэка</span> в участвующих розничных сетях на платформе, а также для повышения уровня учетных записей пользователей для получения дополнительных функций.",
        "retailer": "Преимущества для ритейлера",
        "retailerone": "Повышение <span>узнаваемости бренда</span>",
        "retailertwo": "<span>Увеличение трафика и покупок</span> в интернет–магазинах одежды.",
        "retailerthree": "Ассортимент одежды и сезонные предложения перечислены на самой большой открытой / прозрачной платформе, использующей технологию блокчейн.",
        "retailerfour": "<span>Получите доступ к 50 000 пользователей</span> после запуска, для получения отзывов об ассортименте.",
        "retailerfive": "Аналитика на сайте поможет <span>увеличить продажи за счет оптимизации. </ Span>",
        "retailersix": "Предотвратите мошеннические транзакции и возврат товаров, поскольку пользователи будут проверяться через KYC для установки личности.",
        "retailerseven": "<span>Нулевая комиссия </span> будет установлена в Curate для всех успешных клиентов, что даст ритейлерам большую прибыль, а покупателям - лучшие цены.",
        "retailereight": "<span>QR-коды, поставляемые всем брендам одежды – партнерам </span>, для проверки подлинности по всей цепочке поставок, предотвращая поддельные товары.",
        "lexfuturis": "Curate, включая токены CUR8, представлены международной юридической фирмой и консалтинговой компанией Lex Futurus Group.",
        "policy": "Политика конфиденциальности",
        "howitwrks": "Как это работает",
        "totop": "НАВЕРХ",
        "ambassador": "Амбассадор",
        "usecasehdr": "Как использовать CUR8",
        "usecasetext": "Токены CUR8 служат универсальным служебным токеном, предлагающим пользователям широкий спектр вариантов использования как в Curate DApp, так и вне экосистемы Curate. <br> <br> - Покупка вещей на платформе Curate с использованием токенов CUR8 <br > - Доступ к специальным скидкам – например, скидка 10% на купоны <br> - Погасить бесплатную доставку при совершении покупок на платформе <br> - Обновить аккаунт до Curate Pro, чтобы разблокировать дополнительные функции <br> - Социальная карма для чаевых ритейлеров, предлагающих щедрые бонусы пользователям за обзоры или выполнения определенных действий, например просмотр контента.<br>- Использование в качестве денежной валюты для платежей за пределами экосистемы Curate с нашими партнерами. <br> - Плюс еще многое, что будет добавлено по мере запуска"
      },
      "cn": {
        "ds": "Days",
        "hs": "Hours",
        "ms": "Min",
        "ss": "Sec",
        "ieostart": "ieo starts in",
        "ieoend": "ieo ends",
        "ieo2start": "ieo 2 starts",
        "ieo2end": "ieo 2 ends",
        "ieo3start": "ieo 3 starts",
        "ieo3end": "ieo 3 ends",
        "cookietop": "We use cookies to tailor our services and online advertising.",
        "cookielink": "By using our website you agree with our <a target='_blank' style='color:#ffd788;' href='/cookiepolicy'>Cookie Policy</a>.",
        "about": "About",
        "roadmap": "Roadmap",
        "ourdevs": "Developers",
        "ourteam": "Team",
        "pitch": "Pitch Deck",
        "demo": "Demo",
        "signin": "SIGN IN",
        "header": "The fashion discovery platform",
        "description": "Discover Styles. Earn Crypto.",
        "p2p": "BUY ON P2PB2B (KYC)",
        "airswap": "BUY VIA AIRSWAP (NO KYC)",
        "signin": "SIGN IN",
        "featured": "As featured on",
        "unisex": "UNISEX",
        "abouttext": "<img src='img/sprites/intermediate-svg/mini-logo.svg' alt=''><span>CURATE </span></span></span>is a style discovery decentralized app (DApp) i.e 'blockchain smart contract enabled' platform, which rewards you with digital tokens in the form of BTC, ETH and our own CUR8 tokens in return for users curating fashion styles.",
        "abouttexttwo": "Fashion brands and retailers have partnered up with Curate to showoff their latest styles, raise brand awareness and increase their online sales.",
        "abouttextthree": "In return, Curate provides a trustless platform allowing users to feedback a curated collection of fashion styles for the community to discover.",
        "abouttextfour": "To put simply, Fashion brands partner up with Curate and we pass on the rewards to the curators and discoverer's.",
        "abouttextfive": "We are: Decentralised. Web 3.0. Open Source.",
        "how": "How it works",
        "howtext": "CURATE is based on the ethereum blockchain utilizing the ERC&mdash;20 token system in the form of our utlity token, the CUR8 token.",
        "howtexttwo": "The CURATE platform being a DApp means it's decentralised and distributed system of service is run and hosted by numerous systems around the globe.",
        "howtextthree": "All data in our platform is secured by cryptography. We are decentralised, open source and web 3.0.",
        "howrow": "Content user (i.e brand or fashionista) uploads fashion content to Curate",
        "howrowtwo": "'Curator' community engages and upvotes fashion content",
        "howrowthree": "Content gains popularity allowing 'discoverer' community to discover content",
        "howrowfour": "Curate rewards both original content user, curator and discover users with BTC, ETH and CUR8 tokens",
        "howrowfive": "CUR8 token holders can use the tokens to redeem discount codes, promo offers and more on Curate",
        "demoheader": "Curate Demo Preview",
        "qone": "Concept created by founder, James Hakim",
        "qonetwo": "White paper first draft created",
        "qonethree": "Busines plan first draft completed",
        "qtwo": "Curate team members recruited",
        "qtwotwo": "Website and social media/telegram group created",
        "qtwothree": "Demo preview of platform designed",
        "qthree": "PRE-IEO seed round complete",
        "qthreetwo": "10,000+ telegram members active",
        "qthreethree": "Approved for 1st IEO listing on P2PB2B.io",
        "qfour": "1st IEO starts, aiming to raise $2.25M USD",
        "qfourtwo": "Development officially starts on Curate platform",
        "qfourthree": "CUR8 token is listed on two exchanges, P2PB2B.io and WhiteBit.io and begins trading",
        "twentyqone": "2nd IEO starts on two top CoinMarketCap approved exchanges",
        "twentyqonetwo": "Private-alpha launch of Curate platform open to telegram members",
        "twentyqonethree": "CUR8 token listed on two more top exchanges, volume of trading increase",
        "twentyqtwo": "3rd IEO starts on a DEX",
        "twentyqtwotwo": "Public-beta version launched available to new members",
        "twentyqtwothree": "Curate reaches 10,000 active monthly users using the platform and app",
        "twentyqtwofour": "Start of application development",
        "design": "Chief Design Officer",
        "senioradm": "Senior Administrator",
        "ceo": "Chief Executive Officer &amp; Founder",
        "blockchaindev": "Blockchain Engineer",
        "marketingadv": "Marketing Advisor",
        "salesofficer": "Chief Sales Officer and HR",
        "commmanager": "Chief Community Manager",
        "contmanager": "Content Manager",
        "lawyer": "Certified Blockchain Lawyer",
        "pubrelat": "Head of Public Relations",
        "innovations": "Head of Innovation",
        "smm": "Social Media Manager",
        "digitalmanager": "Social and Digital Manager",
        "operationsman": "Operations Manager",
        "businessofficer": "Chief Business Officer",
        "marketingofficer": "Chief Marketing Officer",
        "retail": "Retail Applicants",
        "exchange": "Exchange Partners",
        "p2pannounce": "Curate is now <span trading platform. P2PB2B is one of the top 20 exchanges in the world with a daily trading volume of",
        "p2pbold": "$418 million - a real powerhouse.",
        "ceocurate": "CEO Curate",
        "distribution": "Token distribution",
        "ieophaseone": "IEO Phase 1",
        "ieophasetwo": "IEO Phase 2",
        "ieophasethree": "IEO Phase 3",
        "ieoteam": "Team",
        "ieopartner": "Partnerships",
        "bounties": "Bounties",
        "commevents": "Community events",
        "fundsalloc": "Funds allocation",
        "development": "Development",
        "marteting": "Marketing",
        "legal": "Legal",
        "bounty": "Bounty &amp; Overhead",
        "banking": "Banking &amp; Reserve",
        "revenue": "Revenue Model",
        "revenueone": "Curate, the original fashion discovery platform, will steadily grow the value of the platform and $CUR8 tokens by increasing demand and use cases by <span>adding new participating retailers, extending niches outside fashion retail via 'Curate +' and by providing enough liquidity.</span>",
        "revenuetwo": "Curate Pro membership for retailers, initial fee $149/year offering retailers enhanced membership <span>including featured listings, verified badge status, more engagement activities such as rewarding users directly with CUR8 tokens.</span> Free to those who opt-in for the affiliate programme i.e amazon associates affiliate, <span>earning curate up to 10% on sales.</span>",
        "revenuethree": "Curate Ads, <span>our in-built native advertising platform offered to advertisers and agencies</span>, allows custom targeting and ad placements to our users who have opted-in yielding a high ROI and RPM.",
        "revenuefour": "Curate +, our native browser extension <span>allows users to earn free BTC and CUR8 as cashback when they shop online through a commission deal.</span> Using our existing partnerships from the curate platform, the Curate + extension extends to all niches outside fashion <span>increasing market adoption of Curate and $CUR8 tokens.</span>",
        "revenuefive": "$CUR8 tokens offered for sale on the platform, which <span>can be used to redeem coupons, get free shipping and get cash back</span> at participating retailers on the platform, as well as level up user accounts for more features.",
        "retailer": "Retailer benefits",
        "retailerone": "Raised <span>brand awareness</span>",
        "retailertwo": "<span>Increased traffic</span> to merchant sites and goal conversions",
        "retailerthree": "Clothing ranges and seasonal wears <span>listed  on the largest open/transparent platform</span> leveraging blockchain technology.",
        "retailerfour": "<span>Access to 50,000 users</span> upon launch for curated feedback on their fashion range.",
        "retailerfive": "On-site analytics and tracking pixel leading to <span>increased sales through optimization.</span>",
        "retailersix": "<span>Prevent fraud transactions </span>and chargebacks as users will be verified <span>via KYC</span> to ensure authenticity.",
        "retailerseven": "<span>Zero commission</span> will be taken from Curate for all successful leads giving retailers bigger profits and customers better prices.",
        "retailereight": "<span>QR barcodes supplied to all partneredclothing brands</span> to verify authenticity throughout the supply chain preventing fake merchandise.",
        "lexfuturis": "Curate including CUR8 tokens are represented by international law firm & consultancy Lex Futurus Group.",
        "policy": "Privacy Policy",
        "howitwrks": "How it works",
        "totop": "TO TOP",
        "ambassador": "Ambassador",
        "usecasehdr": "CUR8 Use Cases",
        "usecasetext": "CUR8 tokens serve as a multi-use utility token offering users a wide<br>number of use cases on both the Curate DApp and outside the Curate ecosystem.<br><br>– Purchase items on the Curate platform using CUR8 tokens<br>– Unlock special discounts on items such as 10% off coupons<br>– Redeem free shipping when shopping on the platform<br>– Upgrade account to Curate Pro to unlock more features<br>– Social karma tipping for retailers to offer bounties to users for reviews or perform certain activities i.e like their content<br>– Use as a monetary currency for payments outside of the Curate ecosystem with our partners.<br>– Plus many more to be added as we go live"
      },
      "vi": {
        "ds": "Ngày",
        "hs": "Giờ",
        "ms": "Phút",
        "ss": "Giây",
        "ieostart": "ieo bắt đầu trong",
        "ieoend": "ieo kết thúc",
        "ieo2start": "ieo 2 bắt đầu",
        "ieo2end": "ieo 2 kết thúc",
        "ieo3start": "ieo 3 bắt đầu",
        "ieo3end": "ieo 3 kết thúc",
        "cookietop": "Chúng tôi sử dụng cookie để điều chỉnh dịch vụ của chúng tôi và quảng cáo trực tuyến.",
        "cookielink": "Thông qua việc sử dụng trang web của chúng tôi, bạn đã đồng ý với các điều khoản của chúng tôi <a target='_blank' style='color:#ffd788;' href='/cookiepolicy'>Cookie Policy</a>.",
        "about": "Về chúng tôi",
        "roadmap": "Lộ Trình",
        "ourdevs": "Nhà phát triển",
        "ourteam": "Đội",
        "pitch": "Pitch Deck",
        "demo": "DEMO",
        "signin": "ĐĂNG NHẬP",
        "header": "Nền tảng khám phá thời trang",
        "description": "Khám phá Phong cách. Nhận tiền điện tử.",
        "p2p": "MUA TRÊN P2PB2B (KYC)",
        "airswap": "MUA QUA AIRSWAP",
        "signin": "ỦY QUYỀN",
        "featured": "Được giới thiệu trên",
        "unisex": "UNISEX",
        "abouttext": "<span><span class='white about__text--first lang'><img src='img/sprites/intermediate-svg/mini-logo.svg' alt=''><span>CURATE </span></span></span>là một ứng dụng phi tập trung khám phá phong cách (DApp), nghĩa là nền tảng ' sử dụng hợp đồng thông minh blockchain ', sẽ thưởng cho bạn các mã thông báo kỹ thuật số dưới dạng BTC, ETH và mã thông báo CUR8 của riêng chúng tôi để đổi lấy phong cách thời trang cho người dùng Curate.",
        "abouttexttwo": "Các thương hiệu thời trang và nhà bán lẻ đã hợp tác với Curate để thể hiện phong cách mới nhất của họ, nâng cao nhận thức về thương hiệu và tăng doanh số bán hàng trực tuyến của họ.",
        "abouttextthree": "Đổi lại, Curate cung cấp một nền tảng 'Trustless' cho phép người dùng đánh giá một bộ sưu tập các kiểu thời trang được quản lý để cộng đồng khám phá.",
        "abouttextfour": "Hiểu đơn giản, các thương hiệu Thời trang hợp tác với Curate và chúng tôi chuyển phần thưởng cho các Curator và người khám phá.",
        "abouttextfive": "Chúng tôi là: Phi Tập Trung. Web 3.0. Mã nguồn mở.",
        "how": "Cách hoạt động",
        "howtext": "CURATE dựa trên blockchain ethereum sử dụng hệ thống mã thông báo ERC & mdash; 20 dưới dạng token tiện ích của chúng tôi, token CUR8.",
        "howtexttwo": "Nền tảng CURATE là một DApp có nghĩa là hệ thống dịch vụ phi tập trung và phân tán được chạy và lưu trữ bởi nhiều hệ thống trên toàn cầu.",
        "howtextthree": "Tất cả dữ liệu trong nền tảng của chúng tôi được bảo mật bằng mật mã. Chúng tôi là phi tập trung, mã nguồn mở và web 3.0.",
        "howrow": "Nội dung của người dùng ( thương hiệu hoặc thời trang) được upload lên Curate",
        "howrowtwo": "Cộng đồng 'Curator' tham gia và upvote nội dung thời trang",
        "howrowthree": "Nội dung được phổ biến cho phép cộng đồng 'discoverer' khám phá nội dung",
        "howrowfour": "Curate thưởng cho cả người sáng tạo nội dung,Curator và người khám phá nội dung bằng BTC, ETH và CUR8",
        "howrowfive": "Chủ sở hữu CUR8 có thể sử dụng token để đổi mã giảm giá, khuyến mại và nhiều thứ khác trên Curate",
        "demoheader": "Xem trước bản DEMO",
        "qone": "Khái niệm được tạo ra bởi người sáng lập của chúng tôi, James Hakim",
        "qonetwo": "Bản phác thảo Whitepaper đâù tiên đươc tạo ra",
        "qonethree": "Bản phác thảo về kế hoạch kinh doanh đầu tiên hoàn thành",
        "qtwo": "Tuyển dụng các thành viên vào đội ngũ Curate",
        "qtwotwo": "Trang web và các kênh phương tiện truyền thông xã hội / nhóm telegram được tạo",
        "qtwothree": "Bản xem trước demo của nền tảng được thiết kế",
        "qthree": "Vòng gọi vốn PRE-IEO seed hoàn thành",
        "qthreetwo": "Hơn 10.000 thành viên telegram hoạt động",
        "qthreethree": "IEO đầu tiên được chấp thuận trên P2PB2B.io",
        "qfour": "Khởi động IEO đầu tiên, với mục tiêu gọi vốn đạt 2,25 triệu đô",
        "qfourtwo": "Nền tảng Curate chính thức được xây dựng",
        "qfourthree": "CUR8 được niêm yết trên hai sàn giao dịch, P2PB2B.io và WhiteBit.io và bắt đầu giao dịch",
        "twentyqone": "Giai đoạn hai IEO bắt đầu trên hai sàn giao dịch được phê duyệt hàng đầu của CoinMarketCap",
        "twentyqonetwo": "Nền tảng Private-alpha của Curate ra mắt đến các thành viên telegram",
        "twentyqonethree": "CUR8 token được niêm yết trên hai sàn giao dịch hàng đầu khác, khối lượng giao dịch tăng",
        "twentyqtwo": "Khởi động giai đoạn 3 IEO trên DEX",
        "twentyqtwotwo": "Bản beta công khai được giới thiệu tới các thành viên mới",
        "twentyqtwothree": "Curate đạt 10.000 người dùng hoạt động hàng tháng sử dụng nền tảng và ứng dụng",
        "twentyqtwofour": "Bắt đầu phát triển ứng dụng",
        "design": "Giám đốc thiết kế",
        "senioradm": "Quản trị viên cấp cao",
        "ceo": "CEO &amp; Nhà sáng lập",
        "blockchaindev": "Kĩ sư Blockchain",
        "marketingadv": "Cố vấn Marketing",
        "salesofficer": "Giám đốc kinh doanh và HR",
        "commmanager": "Giám đốc quản lý cộng đồng",
        "contmanager": "Quản lý nội dung",
        "lawyer": "Luật sư Blockchain đã được chứng nhận",
        "pubrelat": "Trưởng phòng hợp tác",
        "innovations": "Trưởng phòng ý tưởng",
        "smm": "Quản lý truyền thông",
        "digitalmanager": "Quản lý Socical và Digital",
        "operationsman": "Quản lý hoạt động",
        "businessofficer": "Giám đốc kinh doanh",
        "marketingofficer": "Giám đốc Marketing",
        "retail": "Ứng viên bán lẻ",
        "exchange": "Các sàn giao dịch đối tác",
        "p2pannounce": "Curate hiện tại <span class='news-highlight'>đã xác nhận sẽ được niêm yết trên P2PB2B</span> . P2PB2B là một trong Top 20 sàn giao dịch trên thế giới tính theo khối lượng giao dịch hàng ngày",
        "p2pbold": "Khối lượng giao dịch 418 triệu đô",
        "ceocurate": "CEO Curate",
        "distribution": "Phân phối Token",
        "ieophaseone": "IEO giai đoạn 1",
        "ieophasetwo": "IEO giai đoạn 2",
        "ieophasethree": "IEO giai đoạn 3",
        "ieoteam": "Đội Ngũ",
        "ieopartner": "Đối tác",
        "bounties": "Bounty",
        "commevents": "Tổ chức Sự kiện",
        "fundsalloc": "Phân bổ quỹ",
        "development": "Xây dựng và phát triển",
        "marteting": "Marketing",
        "legal": "Pháp Định",
        "bounty": "Chi phí chung &amp; quản trị",
        "banking": "Ngân hàng  &amp; Dự trữ",
        "revenue": "Mô hình doanh thu",
        "revenueone": "Curate, từ nền tảng khám phá thời trang ban đầu, sẽ tăng dần giá trị của nền tảng và mã thông báo $ CUR8 bằng cách tăng nhu cầu và trường hợp sử dụng của token bằng cách <span>thêm các nhà bán lẻ mới, mở rộng thích hợp ngoài bán lẻ thời trang thông qua 'Curate +' và cung cấp đủ thanh khoản.</span>",
        "revenuetwo": "Curate Pro cho các nhà bán lẻ, phí ban đầu là  149 đô la / năm cung cấp cho các nhà bán lẻ nâng cao tư cách thành viên <span>trong đó có danh sách nổi bật, trạng thái huy hiệu được xác minh, nhiều hoạt động tương tác hơn như thưởng cho người dùng trực tiếp bằng mã thông báo CUR8.</span> Miễn phí cho những người chọn tham gia chương trình liên kết, liên kết amazon, <span>kiếm được thu nhập lên tới 10% doanh số với Curate.</span>",
        "revenuethree": "Dịch vụ quảng cáo Curate, <span>nền tảng quảng cáo ban đầu được xây dựng bởi chúng tôi được cung cấp cho các nhà quảng cáo và đại lý</span>,cho phép nhắm mục tiêu tùy chỉnh và quảng cáo cho người dùng mà chúng tôi đã chọn tham gia mang lại hiệu suất ROI và RPM cao.",
        "revenuefour": "Curate +, tiện ích mở rộng trình duyệt của riêng chúng tôi <span>cho phép người dùng kiếm BTC và CUR8 miễn phí dưới dạng tiền hoàn lại khi họ mua sắm trực tuyến thông qua thỏa thuận hoa hồng.</ span> Bằng các mối quan hệ đối tác hiện có của chúng tôi từ nền tảng Curate, tiện ích mở rộng Curate + sẽ lan sâu đến tất cả các ngóc ngách ngoài thời trang <span>giúp tăng thị phần của Curate và mã thông báo $ CUR8.</span>",
        "revenuefive": "Mã thông báo $ CUR8 được chào bán trên nền tảng, trong đó <span>nó có thể được sử dụng để đổi phiếu giảm giá,vận chuyển miễn phí và nhận hoàn lại tiền mặt</span> từ các đại lý bán lẻ tham gia trên nền tảng,cũng như nâng cấp tài khoản người dùng để khám phá nhiều tính năng hơn",
        "retailer": "Lợi ích của đại lý bán lẻ",
        "retailerone": "Nâng cao <span>thương hiệu</span>",
        "retailertwo": "<span>Tăng lưu lượng truy cập</span> đến các trang web bán hàng và chuyển đổi mục tiêu",
        "retailerthree": "Quần áo quy định và theo mùa <span>được liệt kê trên nền tảng mở / minh bạch lớn nhất</span> bằng cách tận dụng công nghệ blockchain.",
        "retailerfour": "<span>Tiếp cận 50k người dùng</span> khi ra mắt để nhận phản hồi về thời trang của họ",
        "retailerfive": "Phân tích tại chỗ và theo dõi pixel làm <span>tăng doanh số bán hàng thông qua tối ưu hóa.</span>",
        "retailersix": "<span>Ngăn chặn giao dịch gian lận </span>và tối ưu các khoản bồi thường vì người dùng sẽ được xác minh thông qua <span>KYC</span> đảm bảo tính xác thực.",
        "retailerseven": "<span>Phí hoa hồng là không</span> được lấy từ Curate cho tất cả các giao dịch thành công tăng lợi nhuận cho các đại lý bán lẻ và giúp khách hàng đạt được mức giá phù hợp ",
        "retailereight": "<span>Mã vạch QR được cung cấp cho tất cả các nhãn hiệu đối tác</span> để xác minh tính xác thực trong toàn bộ chuỗi cung ứng giúp ngăn chặn hàng giả.",
        "lexfuturis": "Curate bao gồm CUR8 token được đại diện bởi công ty luật và tư vấn quốc tế Lex Futurus Group.",
        "policy": "Chính sách Bảo mật",
        "howitwrks": "Cách hoạt động",
        "totop": "Quay về trang đầu",
        "ambassador": "Đại sứ",
        "usecasehdr": "CUR8 và các trường hợp sử dụng",
        "usecasetext": "Mã thông báo CUR8 hoạt động như một token tiện ích đa dụng cung cấp cho người dùng nhiều <br>trường hợp sử dụng trên cả Curate DApp và bên ngoài hệ sinh thái Curate.<br><br> - Mua vật phẩm trên nền tảng Curate bằng cách sử dụng mã thông báo CUR8<br> - Mở khóa giảm giá đặc biệt cho các mặt hàng như phiếu giảm giá 10%<br> - Miễn phí vận chuyển khi mua sắm trên nền tảng<br> - Nâng cấp tài khoản lên Curate Pro để mở khóa nhiều tính năng hơn<br> - Nâng cao sự tín nhiệm cho các nhà bán lẻ cung cấp tiền thưởng cho người dùng đánh giá hoặc thực hiện một số hoạt động nhất định như like nội dung của họ<br> - Sử dụng làm tiền tệ để thanh toán bên ngoài hệ sinh thái Curate với các đối tác của chúng tôi<br> - Và nhiều hơn nữa sẽ được thêm vào khi nền tảng chúng tôi lên sóng "
      },
      "kr": {
        "ds": "Days",
        "hs": "Hours",
        "ms": "Min",
        "ss": "Sec",
        "ieostart": "ieo starts in",
        "ieoend": "ieo ends",
        "ieo2start": "ieo 2 starts",
        "ieo2end": "ieo 2 ends",
        "ieo3start": "ieo 3 starts",
        "ieo3end": "ieo 3 ends",
        "cookietop": "We use cookies to tailor our services and online advertising.",
        "cookielink": "By using our website you agree with our <a target='_blank' style='color:#ffd788;' href='/cookiepolicy'>Cookie Policy</a>.",
        "about": "About",
        "roadmap": "Roadmap",
        "ourdevs": "Developers",
        "ourteam": "Team",
        "pitch": "Pitch Deck",
        "demo": "Demo",
        "signin": "SIGN IN",
        "header": "The fashion discovery platform",
        "description": "Discover Styles. Earn Crypto.",
        "p2p": "BUY ON P2PB2B (KYC)",
        "airswap": "BUY VIA AIRSWAP (NO KYC)",
        "signin": "SIGN IN",
        "featured": "As featured on",
        "unisex": "UNISEX",
        "abouttext": "<img src='img/sprites/intermediate-svg/mini-logo.svg' alt=''><span>CURATE </span></span></span>is a style discovery decentralized app (DApp) i.e 'blockchain smart contract enabled' platform, which rewards you with digital tokens in the form of BTC, ETH and our own CUR8 tokens in return for users curating fashion styles.",
        "abouttexttwo": "Fashion brands and retailers have partnered up with Curate to showoff their latest styles, raise brand awareness and increase their online sales.",
        "abouttextthree": "In return, Curate provides a trustless platform allowing users to feedback a curated collection of fashion styles for the community to discover.",
        "abouttextfour": "To put simply, Fashion brands partner up with Curate and we pass on the rewards to the curators and discoverer's.",
        "abouttextfive": "We are: Decentralised. Web 3.0. Open Source.",
        "how": "How it works",
        "howtext": "CURATE is based on the ethereum blockchain utilizing the ERC&mdash;20 token system in the form of our utlity token, the CUR8 token.",
        "howtexttwo": "The CURATE platform being a DApp means it's decentralised and distributed system of service is run and hosted by numerous systems around the globe.",
        "howtextthree": "All data in our platform is secured by cryptography. We are decentralised, open source and web 3.0.",
        "howrow": "Content user (i.e brand or fashionista) uploads fashion content to Curate",
        "howrowtwo": "'Curator' community engages and upvotes fashion content",
        "howrowthree": "Content gains popularity allowing 'discoverer' community to discover content",
        "howrowfour": "Curate rewards both original content user, curator and discover users with BTC, ETH and CUR8 tokens",
        "howrowfive": "CUR8 token holders can use the tokens to redeem discount codes, promo offers and more on Curate",
        "demoheader": "Curate Demo Preview",
        "qone": "Concept created by founder, James Hakim",
        "qonetwo": "White paper first draft created",
        "qonethree": "Busines plan first draft completed",
        "qtwo": "Curate team members recruited",
        "qtwotwo": "Website and social media/telegram group created",
        "qtwothree": "Demo preview of platform designed",
        "qthree": "PRE-IEO seed round complete",
        "qthreetwo": "10,000+ telegram members active",
        "qthreethree": "Approved for 1st IEO listing on P2PB2B.io",
        "qfour": "1st IEO starts, aiming to raise $2.25M USD",
        "qfourtwo": "Development officially starts on Curate platform",
        "qfourthree": "CUR8 token is listed on two exchanges, P2PB2B.io and WhiteBit.io and begins trading",
        "twentyqone": "2nd IEO starts on two top CoinMarketCap approved exchanges",
        "twentyqonetwo": "Private-alpha launch of Curate platform open to telegram members",
        "twentyqonethree": "CUR8 token listed on two more top exchanges, volume of trading increase",
        "twentyqtwo": "3rd IEO starts on a DEX",
        "twentyqtwotwo": "Public-beta version launched available to new members",
        "twentyqtwothree": "Curate reaches 10,000 active monthly users using the platform and app",
        "twentyqtwofour": "Start of application development",
        "design": "Chief Design Officer",
        "senioradm": "Senior Administrator",
        "ceo": "Chief Executive Officer &amp; Founder",
        "blockchaindev": "Blockchain Engineer",
        "marketingadv": "Marketing Advisor",
        "salesofficer": "Chief Sales Officer and HR",
        "commmanager": "Chief Community Manager",
        "contmanager": "Content Manager",
        "lawyer": "Certified Blockchain Lawyer",
        "pubrelat": "Head of Public Relations",
        "innovations": "Head of Innovation",
        "smm": "Social Media Manager",
        "digitalmanager": "Social and Digital Manager",
        "operationsman": "Operations Manager",
        "businessofficer": "Chief Business Officer",
        "marketingofficer": "Chief Marketing Officer",
        "retail": "Retail Applicants",
        "exchange": "Exchange Partners",
        "p2pannounce": "Curate is now <span class='news-highlight'>confirmed to be listed on P2PB2B</span> trading platform. P2PB2B is one of the top 20 exchanges in the world with a daily trading volume of",
        "p2pbold": "$418 million - a real powerhouse.",
        "ceocurate": "CEO Curate",
        "distribution": "Token distribution",
        "ieophaseone": "IEO Phase 1",
        "ieophasetwo": "IEO Phase 2",
        "ieophasethree": "IEO Phase 3",
        "ieoteam": "Team",
        "ieopartner": "Partnerships",
        "bounties": "Bounties",
        "commevents": "Community events",
        "fundsalloc": "Funds allocation",
        "development": "Development",
        "marteting": "Marketing",
        "legal": "Legal",
        "bounty": "Bounty &amp; Overhead",
        "banking": "Banking &amp; Reserve",
        "revenue": "Revenue Model",
        "revenueone": "Curate, the original fashion discovery platform, will steadily grow the value of the platform and $CUR8 tokens by increasing demand and use cases by <span>adding new participating retailers, extending niches outside fashion retail via 'Curate +' and by providing enough liquidity.</span>",
        "revenuetwo": "Curate Pro membership for retailers, initial fee $149/year offering retailers enhanced membership <span>including featured listings, verified badge status, more engagement activities such as rewarding users directly with CUR8 tokens.</span> Free to those who opt-in for the affiliate programme i.e amazon associates affiliate, <span>earning curate up to 10% on sales.</span>",
        "revenuethree": "Curate Ads, <span>our in-built native advertising platform offered to advertisers and agencies</span>, allows custom targeting and ad placements to our users who have opted-in yielding a high ROI and RPM.",
        "revenuefour": "Curate +, our native browser extension <span>allows users to earn free BTC and CUR8 as cashback when they shop online through a commission deal.</span> Using our existing partnerships from the curate platform, the Curate + extension extends to all niches outside fashion <span>increasing market adoption of Curate and $CUR8 tokens.</span>",
        "revenuefive": "$CUR8 tokens offered for sale on the platform, which <span>can be used to redeem coupons, get free shipping and get cash back</span> at participating retailers on the platform, as well as level up user accounts for more features.",
        "retailer": "Retailer benefits",
        "retailerone": "Raised <span>brand awareness</span>",
        "retailertwo": "<span>Increased traffic</span> to merchant sites and goal conversions",
        "retailerthree": "Clothing ranges and seasonal wears <span>listed  on the largest open/transparent platform</span> leveraging blockchain technology.",
        "retailerfour": "<span>Access to 50,000 users</span> upon launch for curated feedback on their fashion range.",
        "retailerfive": "On-site analytics and tracking pixel leading to <span>increased sales through optimization.</span>",
        "retailersix": "<span>Prevent fraud transactions </span>and chargebacks as users will be verified <span>via KYC</span> to ensure authenticity.",
        "retailerseven": "<span>Zero commission</span> will be taken from Curate for all successful leads giving retailers bigger profits and customers better prices.",
        "retailereight": "<span>QR barcodes supplied to all partneredclothing brands</span> to verify authenticity throughout the supply chain preventing fake merchandise.",
        "lexfuturis": "Curate including CUR8 tokens are represented by international law firm & consultancy Lex Futurus Group.",
        "policy": "Privacy Policy",
        "howitwrks": "How it works",
        "totop": "TO TOP",
        "ambassador": "Ambassador",
        "usecasehdr": "CUR8 Use Cases",
        "usecasetext": "CUR8 tokens serve as a multi-use utility token offering users a wide<br>number of use cases on both the Curate DApp and outside the Curate ecosystem.<br><br>– Purchase items on the Curate platform using CUR8 tokens<br>– Unlock special discounts on items such as 10% off coupons<br>– Redeem free shipping when shopping on the platform<br>– Upgrade account to Curate Pro to unlock more features<br>– Social karma tipping for retailers to offer bounties to users for reviews or perform certain activities i.e like their content<br>– Use as a monetary currency for payments outside of the Curate ecosystem with our partners.<br>– Plus many more to be added as we go live"
      }
    };